name: ESLint Check

on: 
  pull_request:
    branches:
      - feature/eslint 

jobs:
  eslint:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
            node-version: 16

      - name: NPM Install
        run: npm ci

      - name: ESLint
        run: npm run lint
